package com.epam.esm.service.exception;

public enum ServiceError {
    UNEXPECTED_ERROR,
    CERTIFICATE_VALIDATION_FAILURE,
    TAG_VALIDATION_FAILURE,
    DUPLICATE_TAG_NAME,
    BAD_KEY,
    DUPLICATE_CERTIFICATE_TAG,
    BAD_SORT_PROPERTY
}
